### PR TITLE
added landscape not supported message on mobile

### PR DESCRIPTION
**Pull request by safin-sys**

### CODE REVIEW

**Review by dcallus — APPROVED** [review]
Thank you 👍 👍

**Comment by dcallus** [comment]
@safin-sys - Hi there

I've just temporarily reverted this due to the fact that 'Landscape mode not available' pops up briefly on my desktop (mac - brave browser). Doesn't seem to be a problem on my mobile.

Otherwise it's great. Do you have a fix in mind?

Thanks

**Comment by safin-sys** [comment]
This is happening because the CSS is loading after HTML, this can be prevented by putting the CSS directly in index.html. If you have a better fix in mind lmk.

**Comment by dcallus** [comment]
> This is happening because the CSS is loading after HTML, this can be prevented by putting the CSS directly in index.html. If you have a better fix in mind lmk.

This makes sense. Thanks.

I've remerged the branch and added the css to the head of index.html. Seems like a fine solution to me as it's not a huge amount of code to have here.

Thanks a lot :)

**Pull request merged**
